# Generated by Django 4.2.9 on 2024-01-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_monthly_installment_alter_loan_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.FloatField(),
        ),
    ]
