# Generated by Django 4.2.9 on 2024-01-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_customer'),
        ('loan', '0004_loan_approved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='approved_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='emi_paidontime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default='2022-01-01'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
